config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root to: 'people#index'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :people, only: [:index], concerns: :paginatable
  resources :subscriptions, only: [:index, :create, :destroy], concerns: :paginatable

  devise_for :users
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/followed_person.rb
# frozen_string_literal: true

class FollowedPerson < ApplicationRecord
  has_many :subscriptions
  has_many :users, through: :subscriptions
  has_many :followed_person_change_logs
end

app/models/followed_person_change_log.rb
# frozen_string_literal: true

class FollowedPersonChangeLog < ApplicationRecord
  enum action: {
    added: 'The person has been added to the database',
    removed: 'The person has been removed from the database',
    changed_citizenship: 'The person citizenship has been changed',
    changed_sanctions_end_date: 'The person sanctions end date has been changed'
  }
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  belongs_to :provider

  searchkick text_middle: [:first_name, :last_name], callbacks: false
end

app/models/provider.rb
# frozen_string_literal: true

class Provider < ApplicationRecord
  has_many :people

  validates :name, presence: true
  validates :url, presence: true
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :followed_person
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :omniauthable
  devise :confirmable, :database_authenticatable, :recoverable, :registerable, :rememberable, :trackable, :validatable

  has_many :subscriptions
  has_many :followed_people, through: :subscriptions
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_host
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
    def user_not_authorized
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_to(request.referrer || root_path)
    end

    def set_host
      ActionMailer::Base.default_url_options = {
        host: request.protocol + request.host_with_port
      }
      ActionMailer::Base.asset_host = request.protocol + request.host_with_port
    end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  def index
    @providers = Provider.order(:name).all
    search_by = params[:search] || '*'
    provider_ids = params[:providers] || @providers.ids
    @people = Person.search(search_by,
                            fields: [:first_name, :last_name],
                            where: { provider_id: provider_ids },
                            misspellings: false,
                            match: :text_middle,
                            load: false,
                            page: params[:page],
                            per_page: 10)

    query = @people
              .map { 'followed_people.first_name=? AND followed_people.last_name=? AND followed_people.birthday=?' }
              .join(' OR ')

    query_params = @people.reduce([]) { |q_p, p| q_p + [p.first_name, p.last_name, p.birthday] }

    @followed_ids = Subscription
                      .joins(:user)
                      .joins(:followed_person)
                      .where(user: current_user.id)
                      .where(query, *query_params)
                      .each_with_object({}) do |subscription, ids|
      f_p = subscription.followed_person

      p_id = @people.filter_map do |p|
        p.id if p.first_name == f_p.first_name && p.last_name == f_p.last_name && p.birthday == f_p.birthday.to_s
      end.first

      ids[p_id] = f_p.id.to_s if p_id.present?
    end
  end
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  def index
    @followed_people = current_user.followed_people.page(params[:page])
  end

  def create
    p create_params
    followed_person = FollowedPerson.where(create_params).first_or_create

    current_user.followed_people << followed_person unless current_user.followed_people.include?(followed_person)

    flash[:notice] = "You started following #{followed_person.first_name} #{followed_person.last_name}"
    redirect_to request.referer
  end

  def destroy
    followed_person = FollowedPerson.find(params[:id])

    current_user.followed_people.delete(followed_person) if current_user.followed_people.include?(followed_person)

    flash[:notice] = "You stopped following #{followed_person.first_name} #{followed_person.last_name}"
    redirect_to request.referer
  end

  private
    def create_params
      params.require(:person).permit([:first_name, :last_name, :birthday, :citizenship, :end_sanctions_time])
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

module DeviseHelper
  def bootstrap_devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |message| content_tag(:li, message) }.join
    sentence = I18n.t(
      'errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase
    )

    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h5 class="alert-heading">#{sentence}</h4>
      <ul class="mb-0">#{messages}</ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SanctionsAggregator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/"><strong>Sanctions Aggregator</strong></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <% if current_user.present? %>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <strong><%= current_user.email %></strong>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                  <li>
                    <%= link_to 'Subscriptions',
                                subscriptions_path,
                                class: 'dropdown-item' %>
                  </li>
                  <li>
                    <%= link_to 'Logout',
                                destroy_user_session_path,
                                method: :delete,
                                class: 'dropdown-item'%>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </nav>
    <div class="p-1">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
          <%= value %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
        </div>
      <% end %>
    </div>
    <main>
      <div class="py-5 container">
        <%= content_for?(:content) ? yield(:content) : yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<% content_for :content do %>
  <div class="card col-sm-6 offset-sm-3 mt-5">
    <div class="card-header">
      <%= content_for?(:card_header) ? yield(:card_header) : '' %>
    </div>
    <div class="card-body">
      <%= content_for?(:card_body) ? yield(:card_body) : '' %>
    </div>
  </div>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/people/_search_form.erb
<%= form_tag(people_path, method: :get, class: 'form-inline col-sm-12 mt-2') do %>
  <div class="input-group">
    <%= text_field_tag(:search,
                       params[:search],
                       autocomplete: 'off',
                       required: true,
                       placeholder: 'Type something to search ...',
                       class: 'form-control') %>
    <button class="btn btn-primary btn" type="submit">
      <span aria-hidden="true" class="fa fa-search"></span>
    </button>
  </div>
  <div class="input-group mt-3">
    <% @providers.each do |provider| %>
      <div class="form-check me-3">
        <%= check_box_tag('providers[]',
                          provider.id,
                          params[:providers]&.include?(provider.id.to_s) || params[:providers].nil?,
                          multiple: true,
                          id: "provider_#{provider.id}",
                          class: 'form-check-input ml-3') %>
        <%= label_tag "provider_#{provider.id}",
                      provider.name,
                      class: 'form-check-label' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/people/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h1 class="mb-4">Sanctioned People</h1>
      <span class="me-3">Found: <%= pluralize(@people.total_count, 'person') %></span>
      <%= link_to('Reset search filter', root_path) if params[:search].present? || params[:providers].present? %>
    </div>
    <div class="col-sm-6">
      <%= render 'search_form'%>
    </div>
  </div>
  <div class="row">
    <table class="table table-striped my-5">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Date Of Birth</th>
          <th>Citizenship</th>
          <th>End Sanctions Time</th>
          <th>Followed</th>
        </tr>
      </thead>

      <tbody>
      <% @people.each do |person| %>
        <tr>
          <td><%= person.first_name %></td>
          <td><%= person.last_name %></td>
          <td><%= person.birthday %></td>
          <td><%= person.citizenship %></td>
          <td><%= person.end_sanctions_time %></td>
          <td class="py-0">
            <% if @followed_ids.keys.include?(person.id) %>
              <%= button_to 'Yes',
                            subscription_path(id: @followed_ids[person.id]),
                            method: :delete,
                            remote: true,
                            class: 'btn btn-link' %>
            <% else %>
              <%= button_to 'No',
                            subscriptions_path(person: person),
                            remote: true,
                            class: 'btn btn-link' %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="container pagination justify-content-center">
      <%= paginate @people, pagination_class: "pagination-sm" %>
    </div>
  </div>
</div>

app/views/subscriptions/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="mb-4">Followed People</h1>
  </div>
  <div class="row">
    <table class="table table-striped my-5">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Date Of Birth</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @followed_people.each do |person| %>
        <tr>
          <td><%= person.first_name %></td>
          <td><%= person.last_name %></td>
          <td><%= person.birthday %></td>
          <td class="py-0">
            <%= button_to 'Unfollow',
                          subscription_path(id: person.id),
                          method: :delete,
                          remote: true,
                          class: 'btn btn-link'%>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="container pagination justify-content-center">
      <%= paginate @followed_people, pagination_class: "pagination-sm" %>
    </div>
  </div>
</div>